"""Add estimated_value to assets

Revision ID: 1b8713a1df77
Revises: 
Create Date: 2026-02-02 22:22:51.197911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8713a1df77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('estimated_value', sa.Float(), nullable=True))
    op.add_column('assignments', sa.Column('condition_photo_url', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('event_tags', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'photo_url')
    op.drop_column('assignments', 'event_tags')
    op.drop_column('assignments', 'condition_photo_url')
    op.drop_column('assets', 'estimated_value')
    # ### end Alembic commands ###
