"""
PDF rendering for audit reports.

A summary page an auditor can file on its own, then the table, landscape so
the custody columns fit. The summary carries the data fingerprint: the SHA-256
of the same report as CSV, so the two formats can be matched to each other.
"""

import io
from dataclasses import dataclass
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    LongTable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from xml.sax.saxutils import escape

from app.core.audit_reports import Report

INK = colors.HexColor("#06140E")
MUTED = colors.HexColor("#5B6B63")
HAIRLINE = colors.HexColor("#D5DDD8")
EMERALD = colors.HexColor("#10B981")


@dataclass
class ReportContext:
    """Who ran the report and for whom. Not part of the data fingerprint."""

    org_name: str
    generated_by: str
    item_name: Optional[str] = None


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Title"], alignment=0, fontSize=22, leading=26, textColor=INK),
        "label": ParagraphStyle("label", parent=base["Normal"], fontSize=8, leading=10, textColor=MUTED),
        "value": ParagraphStyle("value", parent=base["Normal"], fontSize=11, leading=14, textColor=INK),
        "mono": ParagraphStyle("mono", parent=base["Code"], fontSize=8, leading=10, leftIndent=0, textColor=INK),
        "cell": ParagraphStyle("cell", parent=base["Normal"], fontSize=7.5, leading=9.5, textColor=INK),
        "head": ParagraphStyle("head", parent=base["Normal"], fontName="Helvetica-Bold", fontSize=7.5, leading=9.5, textColor=MUTED),
        "note": ParagraphStyle("note", parent=base["Normal"], fontSize=8.5, leading=11, textColor=MUTED),
    }


def _summary(report: Report, context: ReportContext, styles) -> list:
    covers = f"{context.item_name} only" if context.item_name else "All items"
    facts = [
        ("Organization", context.org_name),
        ("Period", f"{report.start.isoformat()} to {report.end.isoformat()} (UTC, inclusive)"),
        ("Covers", covers),
        ("Rows", str(len(report.rows))),
        ("Generated", report.generated_at.strftime("%Y-%m-%d %H:%M UTC")),
        ("Generated by", context.generated_by),
    ]
    table = Table(
        [[Paragraph(escape(label), styles["label"]), Paragraph(escape(value), styles["value"])] for label, value in facts],
        colWidths=[1.6 * inch, 7 * inch],
        hAlign="LEFT",
    )
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, HAIRLINE),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))

    return [
        Paragraph("Steward", styles["label"]),
        Spacer(1, 4),
        Paragraph(escape(report.title), styles["title"]),
        Spacer(1, 18),
        table,
        Spacer(1, 22),
        Paragraph("Data fingerprint (SHA-256 of this report as CSV)", styles["label"]),
        Spacer(1, 3),
        Paragraph(report.data_fingerprint, styles["mono"]),
        Spacer(1, 14),
        Paragraph(
            "Steward's activity log is add-only: entries cannot be edited or removed. "
            "A CSV export of the same report and period carries the same fingerprint. "
            "Every export is itself recorded in Steward.",
            styles["note"],
        ),
    ]


def _table(report: Report, styles, width: float) -> list:
    columns = [column for column in report.columns if column.in_pdf]
    if not report.rows:
        return [Paragraph("No records in this period.", styles["value"])]

    header = [Paragraph(escape(column.title), styles["head"]) for column in columns]
    body = [
        [Paragraph(escape(row.get(column.key, "")), styles["cell"]) for column in columns]
        for row in report.rows
    ]
    # Free-text columns get the room; the rest share what is left evenly.
    wide = {"notes", "details", "item"}
    weights = [2.2 if column.key in wide else 1.0 for column in columns]
    col_widths = [width * weight / sum(weights) for weight in weights]

    table = LongTable([header] + body, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, 0), 0.8, INK),
        ("LINEBELOW", (0, 1), (-1, -1), 0.3, HAIRLINE),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
    ]))
    return [table]


def render_pdf(report: Report, context: ReportContext) -> bytes:
    buffer = io.BytesIO()
    page = landscape(letter)
    margin = 0.5 * inch
    doc = SimpleDocTemplate(
        buffer,
        pagesize=page,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=margin,
        bottomMargin=0.6 * inch,
        title=f"Steward {report.title}",
        author="Steward",
        # Fixed so the same report renders to the same bytes.
        invariant=1,
    )

    footer_text = f"{report.title} · {context.org_name} · {report.start.isoformat()} to {report.end.isoformat()}"

    def footer(canvas, doc_):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(MUTED)
        canvas.drawString(margin, 0.35 * inch, footer_text)
        canvas.drawRightString(page[0] - margin, 0.35 * inch, f"Page {doc_.page}")
        canvas.setStrokeColor(EMERALD)
        canvas.setLineWidth(1.2)
        canvas.line(margin, page[1] - 0.3 * inch, margin + 0.4 * inch, page[1] - 0.3 * inch)
        canvas.restoreState()

    styles = _styles()
    story = _summary(report, context, styles) + [PageBreak()] + _table(report, styles, page[0] - 2 * margin)
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return buffer.getvalue()
